[package]
name = "vexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
serialport = "4.0.1"
chrono = "0.4.19"
packed_struct = "0.10"